"""initial schema

Revision ID: 3eb743bcb70e
Revises: 
Create Date: 2026-07-01 00:36:38.360235

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb743bcb70e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('ir_url', sa.String(length=1024), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_ticker'), ['ticker'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('scheduled_start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'classified', 'scheduled', 'recording', 'transcribing', 'completed', 'failed', name='eventstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_status'), ['status'], unique=False)

    op.create_table('recording',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'recording', 'finalized', 'failed', name='recordingstatus'), nullable=False),
    sa.Column('s3_prefix', sa.String(length=1024), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recording_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recording_status'), ['status'], unique=False)

    op.create_table('webcast_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('access_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webcast_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webcast_source_event_id'), ['event_id'], unique=True)

    op.create_table('transcript_segment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('speaker', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_segment_recording_id'), ['recording_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segment_recording_id'))

    op.drop_table('transcript_segment')
    with op.batch_alter_table('webcast_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webcast_source_event_id'))

    op.drop_table('webcast_source')
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recording_status'))
        batch_op.drop_index(batch_op.f('ix_recording_event_id'))

    op.drop_table('recording')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_status'))
        batch_op.drop_index(batch_op.f('ix_event_company_id'))

    op.drop_table('event')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_ticker'))

    op.drop_table('company')
    # ### end Alembic commands ###
